### ISSUE TITLE
Remote connection does not respond with classloader/class data on Java 14+

### ISSUE THREAD

**Issue by Col-E** [Col-E/InstrumentationServer#13]
Works on Java 8, 11, does not work on Java 14 or higher.

The agent server seems to track the information just fine, and can construct the appropriate packet, but cannot send the packet over the byte channel.

**Comment by Col-E** [comment]
On the remote process when handling packet responses:
```
java.lang.NoClassDefFoundError: Could not initialize class java.util.concurrent.CompletableFuture
        at software.coley.instrument.sock.WriteResult.<init>(WriteResult.java:16)
        at software.coley.instrument.sock.ChannelHandler.write(ChannelHandler.java:135)
        at software.coley.instrument.Server.lambda$answer$13(Server.java:249)
        at software.coley.instrument.Server.lambda$configureChannel$2(Server.java:184)
        at software.coley.instrument.sock.ChannelHandler.lambda$readLoop$2(ChannelHandler.java:202)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```
Which at face value does not make sense. `CompletableFuture` is 100% going to exist.

**Comment by Col-E** [comment]
The error does not occur when running the server with debug enabled which is quite annoying...

**Comment by Col-E** [comment]
4ced47987f248b7474dc7f8b3f6fdbbead5f9284
